name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-dev socat pkg-config
    
    - name: Check dependencies
      run: make check-deps
    
    - name: Build applications
      run: |
        make clean
        make
    
    - name: Test build artifacts
      run: |
        test -f LAST/last
        test -f BRIDGE/bridge
        test -x LAST/last
        test -x BRIDGE/bridge
    
    - name: Test installation script
      run: |
        chmod +x deploy/install.sh
        # Test dry run (user installation)
        echo "2" | ./deploy/install.sh || true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: last-bridge-${{ matrix.os }}
        path: |
          LAST/last
          BRIDGE/bridge
          README.md
          LICENSE
        retention-days: 30

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-dev socat pkg-config cppcheck
    
    - name: Run static analysis
      run: |
        cppcheck --enable=all --error-exitcode=1 \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction \
          LAST/src/ BRIDGE/src/
    
    - name: Check code formatting
      run: |
        # Check for tabs (should use spaces)
        ! grep -r $'\t' LAST/src/ BRIDGE/src/ || (echo "Found tabs in source code" && exit 1)
        
        # Check for trailing whitespace
        ! grep -r ' $' LAST/src/ BRIDGE/src/ || (echo "Found trailing whitespace" && exit 1)

  create-release:
    name: Create Release Package
    runs-on: ubuntu-latest
    needs: [build-and-test, code-quality]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-dev socat pkg-config
    
    - name: Build applications
      run: |
        make clean
        make
    
    - name: Create source distribution
      run: |
        chmod +x deploy/create-tarball.sh
        ./deploy/create-tarball.sh
    
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/last-bridge-1.0.0.tar.gz
        asset_name: last-bridge-1.0.0.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload release checksums
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/last-bridge-1.0.0.tar.gz.sha256
        asset_name: last-bridge-1.0.0.tar.gz.sha256
        asset_content_type: text/plain

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
